---
- name: Update Linux host
  hosts: all
  serial: 1
  become: true
  tasks:

    - name: Test update_cache
      shell: sudo apt-get update
    - name: Test upgrade
      shell: sudo apt-get upgrade -y
