---
- name: Update Linux host
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Get all updates
      ansible.builtin.apt:
        update_cache: true
        autoremove: true
        autoclean: true
        lock_timeout: 180
    - name: Upgrade all packages on servers
      ansible.builtin.apt:
        name: "*"
        state: latest
