---
- name: Update Linux host
  hosts: all
  serial: 1
  become: true  

  tasks:
    - name: Get all updates
      ansible.builtin.apt:
        update_cache: true
        autoremove: true
        autoclean: true
    - name: Test update_cache
      shell: apt-get update
